// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqczqnuwptrfnavtoxtj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxY3pxbnV3cHRyZm5hdnRveHRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTg5MDMsImV4cCI6MjA2ODY5NDkwM30.NTZi9kMtjK4WUaa4cnLx1UmbJPcXfnZpp0q4COcAsyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});